/**
 
 

reca_Id INT
empl_Id INT
bode_Id INT
tras_Id INT
reca_Fecha DATETIME
reca_Observacion - VARCHAR(200)
reca_Confirmacion CHAR("p","A","R") DEFAULT "p" (pendiente, aprobado, rechazado)
usua_Confirmacion INT
usua_Creacion INT
reca_FechaCreacion DATETIME
usua_Modificacion - INT
reca_FechaModificacion - DATETIME
reca_Estado BIT

reDe_Id INT
reca_Id INT
prod_Id INT
reDe_Cantidad INT
reDe_Observaciones - VARCHAR(200)

prod_DescripcionCorta - VARCHAR(50)
prod_Codigo VARCHAR(20)
prod_Imagen VARCHAR(MAX)






 */